DROP TABLE EXEMPLE IF EXISTS;

CREATE TABLE EXEMPLE (
  ID           BIGINT        NOT NULL AUTO_INCREMENT,
  NOM 	       VARCHAR(255)  NOT NULL,
  DATE_OBJET   DATE 		 NOT NULL,
  DATE_INSERT  DATE 		 NOT NULL,
  PRIMARY KEY (ID)
 );
 